# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'client_window.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(563, 328)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(440, 0, 110, 230))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.get_TMN_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.get_TMN_btn.setCheckable(False)
        self.get_TMN_btn.setObjectName("get_TMN_btn")
        self.verticalLayout.addWidget(self.get_TMN_btn)
        self.send_TMC_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.send_TMC_btn.setObjectName("send_TMC_btn")
        self.verticalLayout.addWidget(self.send_TMC_btn)
        self.jinzhendian_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.jinzhendian_btn.setObjectName("jinzhendian_btn")
        self.verticalLayout.addWidget(self.jinzhendian_btn)
        self.chuancidian_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.chuancidian_btn.setObjectName("chuancidian_btn")
        self.verticalLayout.addWidget(self.chuancidian_btn)
        self.move_jinzhendian_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.move_jinzhendian_btn.setObjectName("move_jinzhendian_btn")
        self.verticalLayout.addWidget(self.move_jinzhendian_btn)
        self.move_chuancidian_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.move_chuancidian_btn.setObjectName("move_chuancidian_btn")
        self.verticalLayout.addWidget(self.move_chuancidian_btn)
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(0, 0, 431, 231))
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 230, 531, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_ip = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_ip.setObjectName("lineEdit_ip")
        self.horizontalLayout.addWidget(self.lineEdit_ip)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.lineEdit_port = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_port.setObjectName("lineEdit_port")
        self.horizontalLayout.addWidget(self.lineEdit_port)
        self.connect_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.connect_btn.setObjectName("connect_btn")
        self.horizontalLayout.addWidget(self.connect_btn)
        self.stop_connect_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.stop_connect_btn.setObjectName("stop_connect_btn")
        self.horizontalLayout.addWidget(self.stop_connect_btn)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 563, 31))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.get_TMN_btn.clicked.connect(MainWindow.get_TMN_btn_clicked)
        self.send_TMC_btn.clicked.connect(MainWindow.send_TMC_btn_clicked)
        self.jinzhendian_btn.clicked.connect(MainWindow.jinzhendian_btn_clicked)
        self.move_jinzhendian_btn.clicked.connect(MainWindow.move_jinzhendian_btn_clicked)
        self.move_chuancidian_btn.clicked.connect(MainWindow.move_chuancidian_btn_clicked)
        self.chuancidian_btn.clicked.connect(MainWindow.chuancidian_btn_clicked)
        self.connect_btn.clicked.connect(MainWindow.connect_btn_clicked)
        self.stop_connect_btn.clicked.connect(MainWindow.stop_connect_btn_clicked)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "模拟客户端"))
        self.get_TMN_btn.setText(_translate("MainWindow", "接收针尖位置"))
        self.send_TMC_btn.setText(_translate("MainWindow", "发射标定向量"))
        self.jinzhendian_btn.setText(_translate("MainWindow", "进针点坐标"))
        self.chuancidian_btn.setText(_translate("MainWindow", "穿刺点坐标"))
        self.move_jinzhendian_btn.setText(_translate("MainWindow", "运动至进针点"))
        self.move_chuancidian_btn.setText(_translate("MainWindow", "运动至穿刺点"))
        self.label.setText(_translate("MainWindow", "IP"))
        self.lineEdit_ip.setText(_translate("MainWindow", "127.0.0.1"))
        self.label_2.setText(_translate("MainWindow", "port"))
        self.lineEdit_port.setText(_translate("MainWindow", "9999"))
        self.connect_btn.setText(_translate("MainWindow", "连接服务器"))
        self.stop_connect_btn.setText(_translate("MainWindow", "断开连接"))

