# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 850)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_joint_control = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_joint_control.setGeometry(QtCore.QRect(10, 530, 491, 261))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.groupBox_joint_control.setFont(font)
        self.groupBox_joint_control.setObjectName("groupBox_joint_control")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox_joint_control)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 30, 491, 227))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.verticalLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.progressBar_3 = QtWidgets.QProgressBar(self.verticalLayoutWidget)
        self.progressBar_3.setMinimum(-170)
        self.progressBar_3.setMaximum(170)
        self.progressBar_3.setProperty("value", 0)
        self.progressBar_3.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar_3.setInvertedAppearance(False)
        self.progressBar_3.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar_3.setObjectName("progressBar_3")
        self.gridLayout.addWidget(self.progressBar_3, 4, 3, 1, 1)
        self.progressBar_6 = QtWidgets.QProgressBar(self.verticalLayoutWidget)
        self.progressBar_6.setMinimum(-120)
        self.progressBar_6.setMaximum(120)
        self.progressBar_6.setProperty("value", 0)
        self.progressBar_6.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar_6.setInvertedAppearance(False)
        self.progressBar_6.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar_6.setObjectName("progressBar_6")
        self.gridLayout.addWidget(self.progressBar_6, 1, 3, 1, 1)
        self.progressBar_1 = QtWidgets.QProgressBar(self.verticalLayoutWidget)
        self.progressBar_1.setMinimum(-170)
        self.progressBar_1.setMaximum(170)
        self.progressBar_1.setProperty("value", 0)
        self.progressBar_1.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar_1.setInvertedAppearance(False)
        self.progressBar_1.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar_1.setObjectName("progressBar_1")
        self.gridLayout.addWidget(self.progressBar_1, 6, 3, 1, 1)
        self.progressBar_2 = QtWidgets.QProgressBar(self.verticalLayoutWidget)
        self.progressBar_2.setMinimum(-120)
        self.progressBar_2.setMaximum(120)
        self.progressBar_2.setProperty("value", 0)
        self.progressBar_2.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar_2.setInvertedAppearance(False)
        self.progressBar_2.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar_2.setObjectName("progressBar_2")
        self.gridLayout.addWidget(self.progressBar_2, 5, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 5, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 5, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 6, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 1, 5, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 2, 5, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 3, 5, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 4, 5, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 5, 5, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 6, 5, 1, 1)
        self.joint_left_button_1 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.joint_left_button_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.joint_left_button_1.setStyleSheet("border-image: url(:/img/img/Arrow_left_normal.png);")
        self.joint_left_button_1.setText("")
        self.joint_left_button_1.setAutoRepeat(True)
        self.joint_left_button_1.setObjectName("joint_left_button_1")
        self.gridLayout.addWidget(self.joint_left_button_1, 6, 2, 1, 1)
        self.joint_left_button_4 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.joint_left_button_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.joint_left_button_4.setStyleSheet("border-image: url(:/img/img/Arrow_left_normal.png);")
        self.joint_left_button_4.setText("")
        self.joint_left_button_4.setAutoRepeat(True)
        self.joint_left_button_4.setObjectName("joint_left_button_4")
        self.gridLayout.addWidget(self.joint_left_button_4, 3, 2, 1, 1)
        self.progressBar_4 = QtWidgets.QProgressBar(self.verticalLayoutWidget)
        self.progressBar_4.setMinimum(-120)
        self.progressBar_4.setMaximum(120)
        self.progressBar_4.setProperty("value", 0)
        self.progressBar_4.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar_4.setInvertedAppearance(False)
        self.progressBar_4.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar_4.setObjectName("progressBar_4")
        self.gridLayout.addWidget(self.progressBar_4, 3, 3, 1, 1)
        self.progressBar_7 = QtWidgets.QProgressBar(self.verticalLayoutWidget)
        self.progressBar_7.setMinimum(-175)
        self.progressBar_7.setMaximum(175)
        self.progressBar_7.setProperty("value", 0)
        self.progressBar_7.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar_7.setInvertedAppearance(False)
        self.progressBar_7.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar_7.setObjectName("progressBar_7")
        self.gridLayout.addWidget(self.progressBar_7, 0, 3, 1, 1)
        self.joint_left_button_6 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.joint_left_button_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.joint_left_button_6.setStyleSheet("border-image: url(:/img/img/Arrow_left_normal.png);")
        self.joint_left_button_6.setText("")
        self.joint_left_button_6.setAutoRepeat(True)
        self.joint_left_button_6.setObjectName("joint_left_button_6")
        self.gridLayout.addWidget(self.joint_left_button_6, 1, 2, 1, 1)
        self.progressBar_5 = QtWidgets.QProgressBar(self.verticalLayoutWidget)
        self.progressBar_5.setMinimum(-170)
        self.progressBar_5.setMaximum(170)
        self.progressBar_5.setProperty("value", 0)
        self.progressBar_5.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar_5.setInvertedAppearance(False)
        self.progressBar_5.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar_5.setObjectName("progressBar_5")
        self.gridLayout.addWidget(self.progressBar_5, 2, 3, 1, 1)
        self.joint_left_button_5 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.joint_left_button_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.joint_left_button_5.setStyleSheet("border-image: url(:/img/img/Arrow_left_normal.png);")
        self.joint_left_button_5.setText("")
        self.joint_left_button_5.setAutoRepeat(True)
        self.joint_left_button_5.setObjectName("joint_left_button_5")
        self.gridLayout.addWidget(self.joint_left_button_5, 2, 2, 1, 1)
        self.joint_left_button_7 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.joint_left_button_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.joint_left_button_7.setStyleSheet("border-image: url(:/img/img/Arrow_left_normal.png);")
        self.joint_left_button_7.setText("")
        self.joint_left_button_7.setAutoRepeat(True)
        self.joint_left_button_7.setAutoExclusive(False)
        self.joint_left_button_7.setObjectName("joint_left_button_7")
        self.gridLayout.addWidget(self.joint_left_button_7, 0, 2, 1, 1)
        self.joint_left_button_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.joint_left_button_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.joint_left_button_2.setStyleSheet("border-image: url(:/img/img/Arrow_left_normal.png);")
        self.joint_left_button_2.setText("")
        self.joint_left_button_2.setAutoRepeat(True)
        self.joint_left_button_2.setObjectName("joint_left_button_2")
        self.gridLayout.addWidget(self.joint_left_button_2, 5, 2, 1, 1)
        self.joint_left_button_3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.joint_left_button_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.joint_left_button_3.setStyleSheet("border-image: url(:/img/img/Arrow_left_normal.png);")
        self.joint_left_button_3.setText("")
        self.joint_left_button_3.setAutoRepeat(True)
        self.joint_left_button_3.setObjectName("joint_left_button_3")
        self.gridLayout.addWidget(self.joint_left_button_3, 4, 2, 1, 1)
        self.joint_right_button_1 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.joint_right_button_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.joint_right_button_1.setStyleSheet("border-image: url(:/img/img/Arrow_right_normal.png);")
        self.joint_right_button_1.setText("")
        self.joint_right_button_1.setAutoRepeat(True)
        self.joint_right_button_1.setObjectName("joint_right_button_1")
        self.gridLayout.addWidget(self.joint_right_button_1, 6, 4, 1, 1)
        self.joint_right_button_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.joint_right_button_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.joint_right_button_2.setStyleSheet("border-image: url(:/img/img/Arrow_right_normal.png);")
        self.joint_right_button_2.setText("")
        self.joint_right_button_2.setAutoRepeat(True)
        self.joint_right_button_2.setObjectName("joint_right_button_2")
        self.gridLayout.addWidget(self.joint_right_button_2, 5, 4, 1, 1)
        self.joint_right_button_3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.joint_right_button_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.joint_right_button_3.setStyleSheet("border-image: url(:/img/img/Arrow_right_normal.png);")
        self.joint_right_button_3.setText("")
        self.joint_right_button_3.setAutoRepeat(True)
        self.joint_right_button_3.setObjectName("joint_right_button_3")
        self.gridLayout.addWidget(self.joint_right_button_3, 4, 4, 1, 1)
        self.joint_right_button_4 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.joint_right_button_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.joint_right_button_4.setStyleSheet("border-image: url(:/img/img/Arrow_right_normal.png);")
        self.joint_right_button_4.setText("")
        self.joint_right_button_4.setAutoRepeat(True)
        self.joint_right_button_4.setObjectName("joint_right_button_4")
        self.gridLayout.addWidget(self.joint_right_button_4, 3, 4, 1, 1)
        self.joint_right_button_5 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.joint_right_button_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.joint_right_button_5.setStyleSheet("border-image: url(:/img/img/Arrow_right_normal.png);")
        self.joint_right_button_5.setText("")
        self.joint_right_button_5.setCheckable(False)
        self.joint_right_button_5.setAutoRepeat(True)
        self.joint_right_button_5.setObjectName("joint_right_button_5")
        self.gridLayout.addWidget(self.joint_right_button_5, 2, 4, 1, 1)
        self.joint_right_button_6 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.joint_right_button_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.joint_right_button_6.setStyleSheet("border-image: url(:/img/img/Arrow_right_normal.png);")
        self.joint_right_button_6.setText("")
        self.joint_right_button_6.setAutoRepeat(True)
        self.joint_right_button_6.setObjectName("joint_right_button_6")
        self.gridLayout.addWidget(self.joint_right_button_6, 1, 4, 1, 1)
        self.joint_right_button_7 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.joint_right_button_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.joint_right_button_7.setStyleSheet("border-image: url(:/img/img/Arrow_right_normal.png);")
        self.joint_right_button_7.setText("")
        self.joint_right_button_7.setAutoRepeat(True)
        self.joint_right_button_7.setObjectName("joint_right_button_7")
        self.gridLayout.addWidget(self.joint_right_button_7, 0, 4, 1, 1)
        self.groupBox_pose = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_pose.setGeometry(QtCore.QRect(10, 0, 491, 301))
        self.groupBox_pose.setObjectName("groupBox_pose")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox_pose)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 25, 491, 274))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_6.addWidget(self.label_15)
        self.lineEdit_joint_out_copy_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.lineEdit_joint_out_copy_button.setObjectName("lineEdit_joint_out_copy_button")
        self.horizontalLayout_6.addWidget(self.lineEdit_joint_out_copy_button)
        self.gridLayout_2.addLayout(self.horizontalLayout_6, 0, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 6, 1, 1, 1)
        self.lineEdit_joint_out = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_joint_out.setObjectName("lineEdit_joint_out")
        self.gridLayout_2.addWidget(self.lineEdit_joint_out, 2, 1, 1, 1)
        self.lineEdit_pose_out = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_pose_out.setObjectName("lineEdit_pose_out")
        self.gridLayout_2.addWidget(self.lineEdit_pose_out, 5, 1, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_20 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_20.setObjectName("label_20")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.label_21 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_21.setObjectName("label_21")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.label_22 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_22.setObjectName("label_22")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_22)
        self.lineEdit_ndi449 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_ndi449.setText("")
        self.lineEdit_ndi449.setObjectName("lineEdit_ndi449")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_ndi449)
        self.lineEdit_ndi340 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_ndi340.setObjectName("lineEdit_ndi340")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_ndi340)
        self.lineEdit_ndi339 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_ndi339.setObjectName("lineEdit_ndi339")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_ndi339)
        self.gridLayout_2.addLayout(self.formLayout, 7, 1, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_7.addWidget(self.label_16)
        self.lineEdit_pose_out_copy_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.lineEdit_pose_out_copy_button.setObjectName("lineEdit_pose_out_copy_button")
        self.horizontalLayout_7.addWidget(self.lineEdit_pose_out_copy_button)
        self.gridLayout_2.addLayout(self.horizontalLayout_7, 3, 1, 1, 1)
        self.groupBox_pose_control = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_pose_control.setGeometry(QtCore.QRect(10, 300, 491, 231))
        self.groupBox_pose_control.setObjectName("groupBox_pose_control")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_pose_control)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 30, 491, 202))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lineEdit_pose_in = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_pose_in.setObjectName("lineEdit_pose_in")
        self.gridLayout_4.addWidget(self.lineEdit_pose_in, 4, 1, 1, 1)
        self.lineEdit_joint_in = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_joint_in.setObjectName("lineEdit_joint_in")
        self.gridLayout_4.addWidget(self.lineEdit_joint_in, 1, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.joint_add_button = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.joint_add_button.setObjectName("joint_add_button")
        self.horizontalLayout.addWidget(self.joint_add_button)
        self.joint_absolute_button = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.joint_absolute_button.setObjectName("joint_absolute_button")
        self.horizontalLayout.addWidget(self.joint_absolute_button)
        self.gridLayout_4.addLayout(self.horizontalLayout, 2, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_18.setObjectName("label_18")
        self.gridLayout_4.addWidget(self.label_18, 3, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_17.setObjectName("label_17")
        self.gridLayout_4.addWidget(self.label_17, 0, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pose_add_button = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pose_add_button.setObjectName("pose_add_button")
        self.horizontalLayout_2.addWidget(self.pose_add_button)
        self.pose_absolute_button = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pose_absolute_button.setObjectName("pose_absolute_button")
        self.horizontalLayout_2.addWidget(self.pose_absolute_button)
        self.gridLayout_4.addLayout(self.horizontalLayout_2, 5, 1, 1, 1)
        self.groupBox_calibrate = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_calibrate.setGeometry(QtCore.QRect(530, 0, 531, 301))
        self.groupBox_calibrate.setObjectName("groupBox_calibrate")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_calibrate)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 30, 531, 271))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textEdit_calibrate = QtWidgets.QTextEdit(self.verticalLayoutWidget_2)
        self.textEdit_calibrate.setObjectName("textEdit_calibrate")
        self.verticalLayout.addWidget(self.textEdit_calibrate)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_23 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_4.addWidget(self.label_23)
        self.lineEdit_calibrate_step = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_calibrate_step.setObjectName("lineEdit_calibrate_step")
        self.horizontalLayout_4.addWidget(self.lineEdit_calibrate_step)
        self.label_24 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_4.addWidget(self.label_24)
        self.lineEdit_calibrate_lengh = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_calibrate_lengh.setObjectName("lineEdit_calibrate_lengh")
        self.horizontalLayout_4.addWidget(self.lineEdit_calibrate_lengh)
        self.label_25 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_4.addWidget(self.label_25)
        self.lineEdit_calibrate_rad = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_calibrate_rad.setObjectName("lineEdit_calibrate_rad")
        self.horizontalLayout_4.addWidget(self.lineEdit_calibrate_rad)
        self.auto_calibrate_button = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.auto_calibrate_button.setObjectName("auto_calibrate_button")
        self.horizontalLayout_4.addWidget(self.auto_calibrate_button)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.manual_calibrate_button = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.manual_calibrate_button.setObjectName("manual_calibrate_button")
        self.horizontalLayout_5.addWidget(self.manual_calibrate_button)
        self.add_calibrate_point_button = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.add_calibrate_point_button.setObjectName("add_calibrate_point_button")
        self.horizontalLayout_5.addWidget(self.add_calibrate_point_button)
        self.finish_manual_calibrate_button = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.finish_manual_calibrate_button.setObjectName("finish_manual_calibrate_button")
        self.horizontalLayout_5.addWidget(self.finish_manual_calibrate_button)
        self.calibrate_error_button = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.calibrate_error_button.setObjectName("calibrate_error_button")
        self.horizontalLayout_5.addWidget(self.calibrate_error_button)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.groupBox_test_function = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_test_function.setGeometry(QtCore.QRect(1070, 0, 121, 771))
        self.groupBox_test_function.setObjectName("groupBox_test_function")
        self.follow_button = QtWidgets.QPushButton(self.groupBox_test_function)
        self.follow_button.setGeometry(QtCore.QRect(10, 30, 99, 27))
        self.follow_button.setObjectName("follow_button")
        self.puncture_test_button = QtWidgets.QPushButton(self.groupBox_test_function)
        self.puncture_test_button.setGeometry(QtCore.QRect(10, 60, 99, 27))
        self.puncture_test_button.setObjectName("puncture_test_button")
        self.groupBox_ct_services = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_ct_services.setGeometry(QtCore.QRect(530, 310, 531, 201))
        self.groupBox_ct_services.setObjectName("groupBox_ct_services")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox_ct_services)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 150, 531, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_7 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_3.addWidget(self.pushButton_7)
        self.pushButton_6 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_3.addWidget(self.pushButton_6)
        self.groupBox_pose_button_contorl = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_pose_button_contorl.setGeometry(QtCore.QRect(520, 520, 541, 261))
        self.groupBox_pose_button_contorl.setObjectName("groupBox_pose_button_contorl")
        self.position_y_add_button = QtWidgets.QPushButton(self.groupBox_pose_button_contorl)
        self.position_y_add_button.setGeometry(QtCore.QRect(100, 70, 61, 71))
        self.position_y_add_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.position_y_add_button.setStyleSheet("border-image: url(:/img/img/ArrowXYZBack_normal.png);")
        self.position_y_add_button.setAutoRepeat(True)
        self.position_y_add_button.setObjectName("position_y_add_button")
        self.position_y_min_button = QtWidgets.QPushButton(self.groupBox_pose_button_contorl)
        self.position_y_min_button.setGeometry(QtCore.QRect(60, 180, 71, 81))
        self.position_y_min_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.position_y_min_button.setStyleSheet("border-image: url(:/img/img/ArrowXYZForward_normal.png);")
        self.position_y_min_button.setAutoRepeat(True)
        self.position_y_min_button.setObjectName("position_y_min_button")
        self.position_x_min_button = QtWidgets.QPushButton(self.groupBox_pose_button_contorl)
        self.position_x_min_button.setGeometry(QtCore.QRect(10, 130, 91, 51))
        self.position_x_min_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.position_x_min_button.setStyleSheet("border-image: url(:/img/img/ArrowXYZLeft_normal.png);")
        self.position_x_min_button.setAutoRepeat(True)
        self.position_x_min_button.setObjectName("position_x_min_button")
        self.position_x_add_button = QtWidgets.QPushButton(self.groupBox_pose_button_contorl)
        self.position_x_add_button.setGeometry(QtCore.QRect(130, 130, 101, 61))
        self.position_x_add_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.position_x_add_button.setStyleSheet("border-image: url(:/img/img/ArrowXYZRight_normal.png);")
        self.position_x_add_button.setAutoRepeat(True)
        self.position_x_add_button.setObjectName("position_x_add_button")
        self.orientation_x_min_button = QtWidgets.QPushButton(self.groupBox_pose_button_contorl)
        self.orientation_x_min_button.setGeometry(QtCore.QRect(280, 120, 91, 51))
        self.orientation_x_min_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.orientation_x_min_button.setStyleSheet("border-image: url(:/img/img/Arrow_left_normal.png);")
        self.orientation_x_min_button.setAutoRepeat(True)
        self.orientation_x_min_button.setObjectName("orientation_x_min_button")
        self.orientation_y_add_button = QtWidgets.QPushButton(self.groupBox_pose_button_contorl)
        self.orientation_y_add_button.setGeometry(QtCore.QRect(370, 30, 51, 91))
        self.orientation_y_add_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.orientation_y_add_button.setStyleSheet("border-image: url(:/img/img/Arrow_Up_normal.png);")
        self.orientation_y_add_button.setAutoRepeat(True)
        self.orientation_y_add_button.setObjectName("orientation_y_add_button")
        self.orientation_x_add_button = QtWidgets.QPushButton(self.groupBox_pose_button_contorl)
        self.orientation_x_add_button.setGeometry(QtCore.QRect(430, 120, 91, 51))
        self.orientation_x_add_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.orientation_x_add_button.setStyleSheet("border-image: url(:/img/img/Arrow_right_normal.png);")
        self.orientation_x_add_button.setAutoRepeat(True)
        self.orientation_x_add_button.setObjectName("orientation_x_add_button")
        self.orientation_y_min_button = QtWidgets.QPushButton(self.groupBox_pose_button_contorl)
        self.orientation_y_min_button.setGeometry(QtCore.QRect(370, 160, 61, 91))
        self.orientation_y_min_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.orientation_y_min_button.setStyleSheet("border-image: url(:/img/img/Arrow_Down_normal.png);")
        self.orientation_y_min_button.setAutoRepeat(True)
        self.orientation_y_min_button.setObjectName("orientation_y_min_button")
        self.position_z_add_button = QtWidgets.QPushButton(self.groupBox_pose_button_contorl)
        self.position_z_add_button.setGeometry(QtCore.QRect(20, 30, 51, 81))
        self.position_z_add_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.position_z_add_button.setStyleSheet("border-image: url(:/img/img/ArrowXYZUp_normal.png);")
        self.position_z_add_button.setAutoRepeat(True)
        self.position_z_add_button.setObjectName("position_z_add_button")
        self.position_z_min_button = QtWidgets.QPushButton(self.groupBox_pose_button_contorl)
        self.position_z_min_button.setGeometry(QtCore.QRect(180, 30, 51, 81))
        self.position_z_min_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.position_z_min_button.setStyleSheet("border-image: url(:/img/img/ArrowXYZDown_normal.png);")
        self.position_z_min_button.setAutoRepeat(True)
        self.position_z_min_button.setObjectName("position_z_min_button")
        self.orientation_z_add_button = QtWidgets.QPushButton(self.groupBox_pose_button_contorl)
        self.orientation_z_add_button.setGeometry(QtCore.QRect(270, 30, 91, 41))
        self.orientation_z_add_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.orientation_z_add_button.setStyleSheet("border-image: url(:/img/img/Pose Arrow Left.png);")
        self.orientation_z_add_button.setAutoRepeat(True)
        self.orientation_z_add_button.setObjectName("orientation_z_add_button")
        self.orientation_z_min_button = QtWidgets.QPushButton(self.groupBox_pose_button_contorl)
        self.orientation_z_min_button.setGeometry(QtCore.QRect(430, 30, 101, 41))
        self.orientation_z_min_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.orientation_z_min_button.setStyleSheet("border-image: url(:/img/img/Pose Arrow Right.png);")
        self.orientation_z_min_button.setAutoRepeat(True)
        self.orientation_z_min_button.setObjectName("orientation_z_min_button")
        self.label_26 = QtWidgets.QLabel(self.groupBox_pose_button_contorl)
        self.label_26.setGeometry(QtCore.QRect(100, 150, 31, 17))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.groupBox_pose_button_contorl)
        self.label_27.setGeometry(QtCore.QRect(380, 130, 31, 17))
        self.label_27.setObjectName("label_27")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 31))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.finish_manual_calibrate_button.clicked.connect(MainWindow.finish_manual_calibrate_button_clicked)
        self.pose_absolute_button.clicked.connect(MainWindow.pose_absolute_button_clicked)
        self.pose_add_button.clicked.connect(MainWindow.pose_add_button_clicked)
        self.manual_calibrate_button.clicked.connect(MainWindow.manual_calibrate_button_clicked)
        self.add_calibrate_point_button.clicked.connect(MainWindow.add_calibrate_point_button_clicked)
        self.joint_add_button.clicked.connect(MainWindow.joint_add_button_clicked)
        self.joint_absolute_button.clicked.connect(MainWindow.joint_absolute_button_clicked)
        self.auto_calibrate_button.clicked.connect(MainWindow.auto_calibrate_button_clicked)
        self.calibrate_error_button.clicked.connect(MainWindow.calibrate_error_button_clicked)
        self.follow_button.clicked.connect(MainWindow.follow_button_clicked)
        self.puncture_test_button.clicked.connect(MainWindow.puncture_test_button_clicked)
        self.joint_right_button_7.clicked.connect(MainWindow.joint_right_button_7_clicked)
        self.position_z_add_button.clicked.connect(MainWindow.position_z_add_button_clicked)
        self.joint_left_button_7.clicked.connect(MainWindow.joint_left_button_7_clicked)
        self.orientation_z_add_button.clicked.connect(MainWindow.orientation_z_add_button_clicked)
        self.lineEdit_joint_out_copy_button.clicked.connect(MainWindow.lineEdit_joint_out_copy_button_clicked)
        self.lineEdit_pose_out_copy_button.clicked.connect(MainWindow.lineEdit_pose_out_copy_button_clicked)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineEdit_joint_out, self.lineEdit_pose_out)
        MainWindow.setTabOrder(self.lineEdit_pose_out, self.lineEdit_ndi449)
        MainWindow.setTabOrder(self.lineEdit_ndi449, self.lineEdit_ndi340)
        MainWindow.setTabOrder(self.lineEdit_ndi340, self.lineEdit_ndi339)
        MainWindow.setTabOrder(self.lineEdit_ndi339, self.lineEdit_joint_in)
        MainWindow.setTabOrder(self.lineEdit_joint_in, self.joint_add_button)
        MainWindow.setTabOrder(self.joint_add_button, self.joint_absolute_button)
        MainWindow.setTabOrder(self.joint_absolute_button, self.lineEdit_pose_in)
        MainWindow.setTabOrder(self.lineEdit_pose_in, self.pose_add_button)
        MainWindow.setTabOrder(self.pose_add_button, self.pose_absolute_button)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "iiwa toolbox"))
        self.groupBox_joint_control.setTitle(_translate("MainWindow", "角关节控制"))
        self.progressBar_3.setFormat(_translate("MainWindow", "%v°"))
        self.progressBar_6.setFormat(_translate("MainWindow", "%v°"))
        self.progressBar_1.setFormat(_translate("MainWindow", "%v°"))
        self.progressBar_2.setFormat(_translate("MainWindow", "%v°"))
        self.label.setText(_translate("MainWindow", "175°"))
        self.label_2.setText(_translate("MainWindow", "轴7:-175°"))
        self.label_3.setText(_translate("MainWindow", "轴6:-120°"))
        self.label_4.setText(_translate("MainWindow", "轴5:-170°"))
        self.label_5.setText(_translate("MainWindow", "轴4:-120°"))
        self.label_6.setText(_translate("MainWindow", "轴3:-170°"))
        self.label_7.setText(_translate("MainWindow", "轴2:-120°"))
        self.label_8.setText(_translate("MainWindow", "轴1:-170°"))
        self.label_9.setText(_translate("MainWindow", "120°"))
        self.label_10.setText(_translate("MainWindow", "170°"))
        self.label_11.setText(_translate("MainWindow", "120°"))
        self.label_12.setText(_translate("MainWindow", "170°"))
        self.label_13.setText(_translate("MainWindow", "120°"))
        self.label_14.setText(_translate("MainWindow", "170°"))
        self.progressBar_4.setFormat(_translate("MainWindow", "%v°"))
        self.progressBar_7.setFormat(_translate("MainWindow", "%v°"))
        self.progressBar_5.setFormat(_translate("MainWindow", "%v°"))
        self.groupBox_pose.setTitle(_translate("MainWindow", "机器人当前位姿"))
        self.label_15.setText(_translate("MainWindow", "各轴角度(a1,a2,a3,a4,a5,a6,a7)"))
        self.lineEdit_joint_out_copy_button.setText(_translate("MainWindow", "复制"))
        self.label_19.setText(_translate("MainWindow", "NDI读数"))
        self.label_20.setText(_translate("MainWindow", "449TCP"))
        self.label_21.setText(_translate("MainWindow", "340钢针"))
        self.label_22.setText(_translate("MainWindow", "339副针"))
        self.label_16.setText(_translate("MainWindow", "TCP空间位姿(x,y,z,rx,ry,rz,rw)四元数"))
        self.lineEdit_pose_out_copy_button.setText(_translate("MainWindow", "复制"))
        self.groupBox_pose_control.setTitle(_translate("MainWindow", "位姿控制"))
        self.joint_add_button.setText(_translate("MainWindow", "关节增量运动"))
        self.joint_absolute_button.setText(_translate("MainWindow", "关节绝对运动"))
        self.label_18.setText(_translate("MainWindow", "笛卡尔空间位姿(x,y,z,rx,ry,rz,rw)四元数"))
        self.label_17.setText(_translate("MainWindow", "各轴角度(a1,a2,a3,a4,a5,a6,a7)"))
        self.pose_add_button.setText(_translate("MainWindow", "位姿增量运动"))
        self.pose_absolute_button.setText(_translate("MainWindow", "位姿绝对运动"))
        self.groupBox_calibrate.setTitle(_translate("MainWindow", "标定"))
        self.textEdit_calibrate.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_23.setText(_translate("MainWindow", "步数"))
        self.lineEdit_calibrate_step.setText(_translate("MainWindow", "10"))
        self.label_24.setText(_translate("MainWindow", "步长(m)"))
        self.lineEdit_calibrate_lengh.setText(_translate("MainWindow", "0.02"))
        self.label_25.setText(_translate("MainWindow", "步长(rad)"))
        self.lineEdit_calibrate_rad.setText(_translate("MainWindow", "0.15"))
        self.auto_calibrate_button.setText(_translate("MainWindow", "自动标定"))
        self.manual_calibrate_button.setText(_translate("MainWindow", "手动标定"))
        self.add_calibrate_point_button.setText(_translate("MainWindow", "增加点"))
        self.finish_manual_calibrate_button.setText(_translate("MainWindow", "结束"))
        self.calibrate_error_button.setText(_translate("MainWindow", "误差勘定"))
        self.groupBox_test_function.setTitle(_translate("MainWindow", "测试功能"))
        self.follow_button.setText(_translate("MainWindow", "针尖跟随"))
        self.puncture_test_button.setText(_translate("MainWindow", "钢针穿刺"))
        self.groupBox_ct_services.setTitle(_translate("MainWindow", "CT通讯"))
        self.pushButton_7.setText(_translate("MainWindow", "连接客户端"))
        self.pushButton_6.setText(_translate("MainWindow", "接收CT点"))
        self.groupBox_pose_button_contorl.setTitle(_translate("MainWindow", "位姿控制"))
        self.position_y_add_button.setText(_translate("MainWindow", "y++"))
        self.position_y_min_button.setText(_translate("MainWindow", "y--"))
        self.position_x_min_button.setText(_translate("MainWindow", "x--"))
        self.position_x_add_button.setText(_translate("MainWindow", "x++"))
        self.orientation_x_min_button.setText(_translate("MainWindow", "x--"))
        self.orientation_y_add_button.setText(_translate("MainWindow", "y++"))
        self.orientation_x_add_button.setText(_translate("MainWindow", "x++"))
        self.orientation_y_min_button.setText(_translate("MainWindow", "y--"))
        self.position_z_add_button.setText(_translate("MainWindow", "z ++"))
        self.position_z_min_button.setText(_translate("MainWindow", "z--"))
        self.orientation_z_add_button.setText(_translate("MainWindow", "z++"))
        self.orientation_z_min_button.setText(_translate("MainWindow", "z--"))
        self.label_26.setText(_translate("MainWindow", "位置"))
        self.label_27.setText(_translate("MainWindow", "姿态"))

import img_rcc_rc
